# Generated by Django 4.2.24 on 2026-03-15 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Wound Care Clinic'), ('research', 'Research Institution')], max_length=20)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HealthcareProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('nurse', 'Wound Care Nurse'), ('mo', 'Medical Officer'), ('co', 'Clinical Officer'), ('surgeon', 'Surgeon'), ('researcher', 'Researcher')], max_length=20)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.facility')),
            ],
        ),
        migrations.CreateModel(
            name='MaggotOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wound_type', models.CharField(max_length=200)),
                ('wound_size', models.CharField(max_length=50)),
                ('urgency', models.CharField(max_length=50)),
                ('larvae_units', models.IntegerField()),
                ('application_type', models.CharField(max_length=50)),
                ('delivery_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('contact_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.facility')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.healthcareprovider')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
