# Generated by Django 4.2.24 on 2026-03-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_facility_healthcareprovider_maggotorder_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='maggotorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='maggotorder',
            name='wound_photo',
            field=models.ImageField(blank=True, null=True, upload_to='wound_images/'),
        ),
    ]
